[server]
url = "https://test.simvue.io"
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpZ25lc2giLCJ0ZW5hbnQiOiJXOFVUWEgzaVNjdkhjR1RpRUZSUjVNIiwibWFuYWdlciI6ZmFsc2UsImFkbWluIjpmYWxzZSwiZXhwIjoxNzM2Njk3NzIxfQ.9qoIKW7WCrwZ22vJwKCB5FBvv_0adkiFLqzpt9OaQ30"